version: '3.8'

services:
  farm-admin-hybrid:
    container_name: farm-admin-hybrid
    build:
      context: .
      dockerfile: Dockerfile.hybrid
      no_cache: false
      pull: true
      args:
        REBUILD_TIMESTAMP: "CLEAN-BUILD"
    ports:
      - "5900:5900"
      - "8080:80"
      - "3333:3001"
      - "2222:22"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=mysql://farmboy:Sntioi004!@mariadb:3306/farmboy_db
      - API_KEY=${API_KEY:-YOUR_FARM_MANAGER_API_KEY_HERE}
      - ETERNALFARM_AGENT_KEY=${ETERNALFARM_AGENT_KEY:-YOUR_ETERNALFARM_AGENT_KEY_HERE}
      - AUTH_AGENT_KEY=${AUTH_AGENT_KEY:-YOUR_AUTH_AGENT_KEY_HERE}
      - ETERNAL_API_URL=${ETERNAL_API_URL:-https://api.eternalfarm.net}
      - ETERNAL_FARM_KEY=${ETERNAL_FARM_KEY:-}
      - ETERNAL_AUTH_KEY=${ETERNAL_AUTH_KEY:-}
      - DISPLAY=:1
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
      - DREAMBOT_USER=${DREAMBOT_USER:-}
      - DREAMBOT_PASS=${DREAMBOT_PASS:-}
      - PROXY_HOST=${PROXY_HOST:-}
      - PROXY_PORT=${PROXY_PORT:-}
      - PROXY_USER=${PROXY_USER:-}
      - PROXY_PASS=${PROXY_PASS:-}
      - VNC_PORT=5900
      - NOVNC_PORT=80
      - JAVA_HOME=/usr/lib/jvm/temurin-8-jdk-amd64
    volumes:
      - farm_data:/app/data
      - dreambot_data:/root/DreamBot
      - ./logs:/var/log
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - farm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - "com.docker.compose.service=farm-admin-hybrid"
      - "io.portainer.stack=farm-admin"

  mariadb:
    container_name: farm-admin-mariadb
    image: lscr.io/linuxserver/mariadb:latest
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=Sntioi004!
      - TZ=Etc/UTC
      - MYSQL_DATABASE=farmboy_db
      - MYSQL_USER=farmboy
      - MYSQL_PASSWORD=Sntioi004!
    volumes:
      - mariadb_data:/config
    ports:
      - "3307:3306"
    restart: unless-stopped
    networks:
      - farm-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pSntioi004!"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    labels:
      - "com.docker.compose.service=mariadb"
      - "io.portainer.stack=farm-admin"

volumes:
  farm_data:
    driver: local
  dreambot_data:
    driver: local
  mariadb_data:
    driver: local

networks:
  farm-network:
    driver: bridge
